# Generated by Django 6.0.3 on 2026-03-28 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('users', '0002_jobvacancy_userprofile_jobmatch_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userprofile'),
        ),
    ]
