# Generated by Django 6.0.2 on 2026-04-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('degree', models.CharField(blank=True, max_length=150, null=True)),
                ('fieldOfStudy', models.CharField(blank=True, max_length=150, null=True)),
                ('graduationYear', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('companyName', models.CharField(blank=True, max_length=255, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rawText', models.TextField(blank=True)),
                ('filePath', models.FileField(upload_to='resume_pdfs/')),
                ('fileType', models.CharField(default='pdf', max_length=10)),
                ('predicted_category', models.CharField(blank=True, default='', max_length=100)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('uploadDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
