# Generated by Django 6.0.2 on 2026-03-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='filePath',
            field=models.FileField(upload_to='resume_pdfs/'),
        ),
    ]
