# Generated by Django 6.0.2 on 2026-04-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='resume',
            name='predicted_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
