# Generated by Django 6.0.3 on 2026-04-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_resume_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='fieldOfStudy',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='user',
        ),
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='resume',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='resume',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='endDate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='startDate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
